package com.example.bilregisterdesktop.Model;

import javafx.beans.property.*;

public class Car {
    private final IntegerProperty id;
    private final StringProperty model;
    private final StringProperty name;
    private final StringProperty status;
    private final StringProperty regNum;
    private final IntegerProperty yearModel;
    private final IntegerProperty price;
    private final IntegerProperty km;

    private CustomerInformation customerInformation; // Ny egenskap
    private final IntegerProperty customer_id;


    public Car(int id, String model, String name, String status, String regNum, int km, int price, int yearModel, int customer_id) { {
        this.id = new SimpleIntegerProperty(id);
        this.model = new SimpleStringProperty(model);
        this.name = new SimpleStringProperty(name);
        this.status = new SimpleStringProperty(status);
        this.regNum = new SimpleStringProperty(regNum);
        this.km = new SimpleIntegerProperty(km);
        this.price = new SimpleIntegerProperty(price);
        this.yearModel = new SimpleIntegerProperty(yearModel);
        this.customer_id = new SimpleIntegerProperty(customer_id);
    }}

    // Getters and setters (generated by your IDE or manually)

    public CustomerInformation getCustomerInformation() {
        return customerInformation;
    }

    public void setCustomerInformation(CustomerInformation customerInformation) {
        this.customerInformation = customerInformation;
    }

    public int getCustomer_id() {
        return customer_id.get();
    }

    public IntegerProperty customer_idProperty() {
        return customer_id;
    }

    public void setCustomer_id(int customer_id) {
        this.customer_id.set(customer_id);
    }

    // Getters and setters (generated by your IDE or manually)
    public int getId() {
        return id.get();
    }

    public void setId(int id) {
        this.id.set(id);
    }

    public IntegerProperty idProperty() {
        return id;
    }

    // Other getters and setters...

    public StringProperty modelProperty() {
        return model;
    }

    public StringProperty nameProperty() {
        return name;
    }

    public StringProperty statusProperty() {
        return status;
    }

    public StringProperty regNumProperty() {
        return regNum;
    }

    public IntegerProperty yearModelProperty() {
        return yearModel;
    }

    public IntegerProperty priceProperty() {
        return price;
    }

    public IntegerProperty kmProperty() {
        return km;
    }

    public int getPrice() {
        return price.get();
    }

    public int getKm() {
        return km.get();
    }

    public String getModel() {
        return model.get();
    }

    public void setModel(String model) {
        this.model.set(model);
    }

    public String getName() {
        return name.get();
    }

    public void setName(String name) {
        this.name.set(name);
    }

    public String getStatus() {
        return status.get();
    }

    public void setStatus(String status) {
        this.status.set(status);
    }

    public String getRegNum() {
        return regNum.get();
    }

    public void setRegNum(String regNum) {
        this.regNum.set(regNum);
    }
}

